# Generated by Django 4.2.5 on 2023-11-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="grade",
            field=models.SmallIntegerField(default=100, null=True),
        ),
    ]
