# Generated by Django 4.2.5 on 2023-11-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120, null=True)),
                ("last_name", models.CharField(max_length=120, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("grade", models.SmallIntegerField(null=True)),
            ],
        ),
    ]
